import { test } from "vite-plus/test";
import fs from "node:fs";
import {
  FILL_OPTIONS,
  HIFI_PASSIVES,
  HIFI_WOOFERS,
  MID_OPTIONS,
  SUB_OPTIONS,
} from "../src/lib/data";
import { publishedText } from "../src/lib/xmax";
import type { PassiveRadiator, ThieleSmall, XmaxBand } from "../src/types";

// Rewrites docs/xmax-audit.md: every driver's published excursion figures, coil and gap heights, and the comparable
// Xmax the models use, so the gaps and estimates stay visible. Run it after changing a driver's excursion data:
//   vp run xmax-audit

type Row = Pick<ThieleSmall, "pub" | "Hvc" | "Hg" | "Xmax" | "xmax"> &
  Pick<PassiveRadiator, "id" | "name"> & { table: string };
const n = (v: number | undefined) => (v == null ? "–" : `${+v.toFixed(2)}`);
const host = (url: string | undefined) =>
  url ? `[${new URL(url).hostname}](${url})` : "table note";

test("write docs/xmax-audit.md", () => {
  const rows: Row[] = [
    ...SUB_OPTIONS.map((d) => ({ table: "Sub", id: d.id, name: d.name, ...d.ts })),
    ...MID_OPTIONS.map((d) => ({ table: "Mid", id: d.id, name: d.name, ...d.ts })),
    ...FILL_OPTIONS.map((d) => ({ table: "Fill", id: d.id, name: d.name, ...d.ts })),
    ...HIFI_WOOFERS.map((d) => ({ table: "Hi-fi", id: d.id, name: d.name, ...d.ts })),
    ...HIFI_PASSIVES.map((d) => ({ table: "Passive", ...d })),
  ];
  const count = (b: XmaxBand["basis"]) => rows.filter((r) => r.xmax.basis === b).length;
  const lines = [
    "# Xmax audit",
    "",
    "Generated by `vp run xmax-audit` (tests/xmax-audit.ts); do not edit by hand.",
    "",
    "The models compare every driver on one scale, (Hvc − Hg)/2 + Hg/4 (see `src/lib/xmax.ts`). **Basis**: derived",
    "from the coil and gap heights; converted from the maker's Xmax and its stated formula; published (a passive",
    "radiator's linear limit, or its mechanical one where that is all the maker gives); or estimated, where the comparable value is the middle of the band shown.",
    "",
    `${rows.length} drivers: ${count("derived")} derived, ${count("converted")} converted, ${count("published")} published, ${count("estimated")} estimated.`,
    "",
    "| table | driver | maker's figures, mm | Hvc | Hg | basis | Xmax used | band | source |",
    "|---|---|---|---|---|---|---|---|---|",
    ...rows.map(
      (r) =>
        `| ${r.table} | ${r.name} (\`${r.id}\`) | ${publishedText(r.pub)} | ${n(r.Hvc)} | ${n(r.Hg)} | ${r.xmax.basis} | ${n(r.Xmax)} | ${r.xmax.lo === r.xmax.hi ? "" : `${n(r.xmax.lo)}–${n(r.xmax.hi)}`} | ${host(r.pub.src)} |`,
    ),
    "",
  ];
  fs.writeFileSync(new URL("../docs/xmax-audit.md", import.meta.url), lines.join("\n"));
});
